### ISSUE TITLE
`com.easypost.easyvcr.TimeFrame` throws Null Errors

### ISSUE THREAD

**Issue by Justintime50** [EasyPost/easyvcr-java#17]
I attempted to integrate the expiration config to the `easypost-java` project and was met with the following error (this error happens for every test, regardless of the TimeFrame used or whether the helper TimeFrame or a manual one was used):

```
[ERROR] testUpdate  Time elapsed: 0.222 s  <<< ERROR!
java.lang.NullPointerException: Cannot invoke "com.easypost.easyvcr.TimeFrame$CommonTimeFrames.ordinal()" because "this.commonTimeFrame" is null
        at com.easypost.CarrierAccountTest.createBasicCarrierAccount(CarrierAccountTest.java:67)
        at com.easypost.CarrierAccountTest.testUpdate(CarrierAccountTest.java:113)
```

I used the code directly from the README, neither option worked:

```java
        AdvancedSettings advancedSettings = new AdvancedSettings();
        advancedSettings.timeFrame = 
                new TimeFrame(30, 0, 0, 0); // Any matching request is considered expired if it was recorded more than 30 days ago
        // or
        advancedSettings.timeFrame =
                TimeFrame.months12(); // Any matching request is considered expired if it was recorded more than a year ago
        advancedSettings.whenExpired = ExpirationActions.ThrowException; // Throw exception if the recording is expired
```

**Comment by nwithan8** [comment]
Turns out switch statements don't handle null enums values in the default case as I would have expected them to.
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/17054780/196859031-d4a4a96b-0ec5-4a91-9372-1290cecd39f3.png">

This has been patched in #16
